Repository mattermost/mattermost-cloud-monitoring, pull requests merged in 2020-10, with the labels that each got.

#175 [MM-29079] Adding prometheus operator helm deployment in post installation module.
  terraform/aws/modules/cluster-post-installation/prometheus_operator.tf
  terraform/aws/modules/cluster-post-installation/providers.tf
Labels: 3: Reviews Complete

#174 [MM-29113] Adding kubernetes secret for thanos objstore configuration.
  terraform/aws/modules/cluster-post-installation/thanos-object-store-secret.tf
Labels: 3: Reviews Complete

#177 [MM-29546] Deploy metrics server in CnC clusters
  terraform/aws/modules/cluster-post-installation/metrics_server.tf
Labels: 3: Reviews Complete

#179 [MM-29697] Use pagination to get all route53 dns names
  lambda-functions/prometheus-dns-registration-service/Gopkg.toml
  lambda-functions/prometheus-dns-registration-service/Makefile
  lambda-functions/prometheus-dns-registration-service/main.go
Labels: 3: Reviews Complete

#178 Create retention in days variable for CW of ES
  terraform/aws/modules/elasticsearch/cloudwatch.tf
  terraform/aws/modules/elasticsearch/elasticsearch.tf
  terraform/aws/modules/elasticsearch/variables.tf
Labels: 2: Infra Review

#180 Add scrape timeout option in the prometheus configuration structure
  lambda-functions/prometheus-dns-registration-service/main.go
Labels: 3: Reviews Complete

#181 Remove evaluation interval
  lambda-functions/prometheus-dns-registration-service/main.go
Labels: 3: Reviews Complete

#183 [MM-29900] Adding Terraform module for Thanos store discovery tool deployment.
  terraform/aws/modules/cluster/worker_iam.tf
  terraform/aws/modules/thanos-store-discovery/thanos_store_discovery.tf
  terraform/aws/modules/thanos-store-discovery/variables.tf
Labels: 3: Reviews Complete

#184 Migrate Grafana chart to official and update from 6.5.2 to 7.2.1
  terraform/aws/modules/cluster-post-installation/grafana.tf
  terraform/aws/modules/cluster-post-installation/providers.tf
  terraform/aws/modules/cluster-post-installation/variables.tf
Labels: 3: Reviews Complete

#187 Update Monitoring and Logging architecture diagrams. Update readme to cover new tooling.
  README.md
  img/logging.png
  img/monitoring.png
  img/prometheus_microservice.png
Labels: 3: Reviews Complete, kind/documentation

#190 create LB alarms for all LBS
  lambda-functions/create-elb-cloudwatch-alarm/main.go
Labels: 2: Infra Review

#192 Create a redirection to use AWS' Elasticsearch Kibana
  terraform/aws/modules/cluster-post-installation/kibana.tf
  terraform/aws/modules/elasticsearch/kibana.tf
  terraform/aws/modules/route53-registration/route53.tf
Labels: 2: Infra Review

#191 [MM-29019] Include helm3 volumes
  terraform/aws/modules/provisioner/provisioner.tf
Labels: 3: Reviews Complete

#189 [MM-29019] Private DNS for mattermost-cloud is removed
  terraform/aws/modules/provisioner/provisioner.tf
  terraform/aws/modules/provisioner/variables.tf
Labels: 3: Reviews Complete
