Repository mattermost/mattermost-cloud-monitoring, pull requests merged in 2020-08, with the labels that each got.

#153 Adding option to select when to deploy R53 record for customer portal
  terraform/aws/modules/customer-web-server/variables.tf
  terraform/aws/modules/customer-web-server/web-server.tf
Labels: 2: Infra Review

#155 MM-27360 Adding security group for PostgreSQL and relevant DB subnet rules
  terraform/aws/modules/subnet-and-networking-3az/security_groups.tf
  terraform/aws/modules/subnet-and-networking/security_groups.tf
Labels: 2: Infra Review

#154 [MM 27333] Enable Teleport external storage in CnC and Gitlab clusters.
  terraform/aws/modules/cluster/aws_auth_configmap.tf
  terraform/aws/modules/cluster/variables.tf
  terraform/aws/modules/cluster/worker_iam.tf
  terraform/aws/modules/eks-cluster/variables.tf
  terraform/aws/modules/eks-cluster/worker_iam.tf
  terraform/aws/modules/teleport/providers.tf
  terraform/aws/modules/teleport/teleport.tf
Labels: 2: Infra Review

#158 [MM 27459] Add new variable to enable check for PostgreSQL/Aurora tag.
  terraform/aws/modules/database-factory-scaling/cloud_db_factory_horizontal_scaling.tf
  terraform/aws/modules/database-factory-scaling/variables.tf
Labels: 2: Infra Review, do-not-merge/awaiting-PR

#159 rds/cloudwatch: filter out multitentant rds
  lambda-functions/create-rds-cloudwatch-alarm/main.go
Labels: 3: Reviews Complete

#160 Adding DB factory permissions to handle creation and deletion of DB Parameter Groups
  terraform/aws/modules/database-factory/database_factory_user_permissions.tf
Labels: 2: Infra Review
