Repository mattermost/mattermost-cloud-monitoring, pull requests merged in 2020-09, with the labels that each got.

#164 [MM-26760]6 Moving kops state buckets to Terraform, adding policy to restrict down state access.
  terraform/aws/modules/provisioner-users/state_bucket.tf
  terraform/aws/modules/provisioner-users/variables.tf
Labels: 3: Reviews Complete

#165 [MM-28092] Cutting direct access to EKS clusters via developers role
  terraform/aws/modules/cluster/aws_auth_configmap.tf
  terraform/aws/modules/cluster/dev_access_iam.tf
  terraform/aws/modules/eks-cluster/aws_auth_configmap.tf
  terraform/aws/modules/eks-cluster/dev_access_iam.tf
Labels: 3: Reviews Complete

#167 Create IAM access ID and secret for provisioner via terraform
  terraform/aws/modules/provisioner/locals.tf
  terraform/aws/modules/provisioner/provisioner.tf
  terraform/aws/modules/provisioner/variables.tf
Labels: 3: Reviews Complete

#166 Small improvements to Atlantis module
  terraform/aws/modules/atlantis/atlantis.tf
  terraform/aws/modules/atlantis/chart_values.yaml
  terraform/aws/modules/atlantis/variables.tf
Labels: 3: Reviews Complete

#168 [MM-28463] Create installation filestore in each VPC.
  terraform/aws/modules/vpc-setup/installation_s3_buckets.tf
Labels: 3: Reviews Complete

#169 [MM-27280] Migrate to new NGINX deployment, general fixes
  terraform/aws/modules/aws-certs/output.tf
  terraform/aws/modules/aws-certs/private_cert.tf
  terraform/aws/modules/aws-certs/public_cert.tf
  terraform/aws/modules/aws-certs/variables.tf
  terraform/aws/modules/customer-web-server/templates/crds.yaml
  terraform/aws/modules/customer-web-server/templates/letsencrypt-clusterissuer-prod.yaml
  terraform/aws/modules/customer-web-server/web-server.tf
  terraform/aws/modules/database-factory/database_factory.tf
  terraform/aws/modules/database-factory/variables.tf
  terraform/aws/modules/nginx/nginx.tf
  terraform/aws/modules/nginx/variables.tf
  terraform/aws/modules/provisioner/certs.tf
  terraform/aws/modules/provisioner/ingress-internal.tf
  terraform/aws/modules/provisioner/provisioner.tf
  terraform/aws/modules/provisioner/route53.tf
  terraform/aws/modules/provisioner/variables.tf
  terraform/aws/modules/route53-registration/route53.tf
  terraform/aws/modules/vpc-setup/installation_s3_buckets.tf
Labels: 2: Infra Review

#171 [MM-28989] Adding permissions for provisioner user to be able to use shared file store.
  terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
Labels: 2: Dev Review

#170 [MM-28888] Updating database factory components and policies
  terraform/aws/modules/database-factory-scaling/cloud_db_factory_vertical_scaling.tf
  terraform/aws/modules/database-factory-scaling/cloud_db_factory_vertical_scaling_user_permissions.tf
  terraform/aws/modules/vpc-setup/cluster_nodes_iam.tf
Labels: 2: Dev Review

#172 [MM-28662] Add long term Prometheus metrics buckets.
  terraform/aws/modules/cluster-post-installation/metrics_bucket.tf
  terraform/aws/modules/cluster/worker_iam.tf
Labels: 3: Reviews Complete

#173 [MM-29080] Adding support for Thanos in private SSL certs.
  terraform/aws/modules/aws-certs/private_cert.tf
  terraform/aws/modules/aws-certs/variables.tf
Labels: 2: Infra Review
