Repository mattermost/mattermost-cloud-monitoring, pull requests merged in 2021-04, with the labels that each got.

#283 [MM-34068] Add cws compliance cronjob and secret updates.
  terraform/aws/modules/customer-web-server/cws_compliance.tf
  terraform/aws/modules/customer-web-server/variables.tf
  terraform/aws/modules/customer-web-server/web-server.tf
Labels: 2: Infra Review

#277 Update image docker hub repo for fluxcloud
  terraform/aws/modules/cluster-post-installation/flux.tf
  terraform/aws/modules/customer-web-server/flux.tf
  terraform/aws/modules/fleet-controller/flux.tf
Labels: 3: Reviews Complete

#285 Fix permissions of database factory user to be able to modify the cluster
  terraform/aws/modules/database-factory/database_factory_user_permissions.tf
Labels: 2: Infra Review, 3: Reviews Complete

#294 Fix atlantis and change the repo config
  terraform/aws/modules/atlantis/chart_values.yaml
Labels: 2: Infra Review

#297 Add cloudwatch alarms for elasticsearch
  terraform/aws/modules/elasticsearch/locals.tf
  terraform/aws/modules/elasticsearch/monitoring.tf
  terraform/aws/modules/elasticsearch/variables.tf
Labels: 2: Infra Review
