Repository mattermost/mattermost-cloud-monitoring, pull requests merged in 2021-01, with the labels that each got.

#227 add conditional to create vpn ingress for RDS both in test and dev
  terraform/aws/modules/subnet-and-networking-3az/security_groups.tf
  terraform/aws/modules/subnet-and-networking/security_groups.tf
Labels: 2: Infra Review

#231 Grafana new dashboards for Bind and RDS metrics
  terraform/aws/modules/cluster-post-installation/grafana_dashboard_configmaps.tf
Labels: 2: Infra Review

#228 Simplification of ES configuration
  terraform/aws/modules/elasticsearch/elasticsearch.tf
  terraform/aws/modules/elasticsearch/variables.tf
Labels: 2: Infra Review

#239 Lambda function and infrastructure components to monitor RDS Cluster Alerts
  .circleci/config.yml
  lambda-functions/rds-cluster-events/Makefile
  lambda-functions/rds-cluster-events/go.mod
  lambda-functions/rds-cluster-events/go.sum
  lambda-functions/rds-cluster-events/main.go
  lambda-functions/rds-cluster-events/response.go
  terraform/aws/modules/rds-cluster-events/rds-cluster.events.tf
  terraform/aws/modules/rds-cluster-events/variables.tf
Labels: 2: Infra Review

#238 MM-31294: Terraform module for budgets
  terraform/aws/modules/billing/budget.tf
  terraform/aws/modules/billing/variables.tf
Labels: 2: Infra Review

#234 MM-31881: Add cluster autoscaler to EKS clusters
  terraform/aws/modules/cluster-post-installation/cluster-autoscaler.tf
  terraform/aws/modules/cluster/worker_asg.tf
  terraform/aws/modules/cluster/worker_iam.tf
Labels: 2: Infra Review

#243 [MM-31728] Migrating database factory in dedicated namespace.
  terraform/aws/modules/database-factory-scaling/cloud_db_factory_horizontal_scaling.tf
  terraform/aws/modules/database-factory-scaling/cloud_db_factory_vertical_scaling.tf
  terraform/aws/modules/database-factory-scaling/variables.tf
  terraform/aws/modules/database-factory/database_factory.tf
  terraform/aws/modules/database-factory/variables.tf
Labels: 2: Infra Review

#246 Fix typo
  terraform/aws/modules/flux/output.tf
Labels: kind/documentation

#247 Adding Gitlab OAUTH token for utilities
  terraform/aws/modules/provisioner/provisioner.tf
  terraform/aws/modules/provisioner/variables.tf
Labels: 3: Reviews Complete

#241 Add logging to EKS master
  terraform/aws/modules/cluster/master.tf
  terraform/aws/modules/cluster/variables.tf
  terraform/aws/modules/eks-cluster/master.tf
  terraform/aws/modules/eks-cluster/variables.tf
Labels: 2: Infra Review
