Repository mattermost/mattermost-cloud-monitoring, pull requests merged in 2021-02, with the labels that each got.

#250 Added BLAPI settings for the CWS secret
  terraform/aws/modules/customer-web-server/variables.tf
  terraform/aws/modules/customer-web-server/web-server.tf
Labels: 3: Reviews Complete

#251 [MM-32631] Adding fleet controller cronjob module
  terraform/aws/modules/fleet-controller/fleet_controller.tf
  terraform/aws/modules/fleet-controller/variables.tf
Labels: 2: Dev Review, 2: Infra Review

#254 MM-32796: Add SuspendProcesses
  terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
Labels: 2: Infra Review

#256 [MM-32759] Add lambda that will monitor account and create alerts.
  .circleci/config.yml
  lambda-functions/account-alerts/Makefile
  lambda-functions/account-alerts/go.mod
  lambda-functions/account-alerts/go.sum
  lambda-functions/account-alerts/main.go
  lambda-functions/account-alerts/notification.go
  terraform/aws/modules/account-alerts/account_alerts.tf
  terraform/aws/modules/account-alerts/variables.tf
Labels: 3: Reviews Complete

#255 MM-32486: Deckhand
  .circleci/config.yml
  lambda-functions/cleanup-unused-images/Makefile
  lambda-functions/cleanup-unused-images/go.mod
  lambda-functions/cleanup-unused-images/go.sum
  lambda-functions/cleanup-unused-images/main.go
  terraform/aws/modules/cleanup-unused-images/cloudwatch.tf
  terraform/aws/modules/cleanup-unused-images/iam.tf
  terraform/aws/modules/cleanup-unused-images/lambdas.tf
  terraform/aws/modules/cleanup-unused-images/variables.tf
Labels: 2: Dev Review, 2: Infra Review

#266 Compute time.now before jumping into the loop for filtering images
  lambda-functions/deckhand/main.go
Labels: 2: Dev Review
